DROP TABLE MBS_SEN_MEMBER CASCADE CONSTRAINTS;
DROP TABLE MBS_PRO_MEMBER CASCADE CONSTRAINTS;
DROP TABLE MBS_SURVEY CASCADE CONSTRAINTS;
DROP TABLE MBS_RESULT_SURVEY CASCADE CONSTRAINTS;
DROP TABLE MBS_BOARD_INQU CASCADE CONSTRAINTS;
DROP TABLE MBS_INQU_ADMIN CASCADE CONSTRAINTS;
DROP TABLE MBS_BOARD_COMMU CASCADE CONSTRAINTS;
DROP TABLE MBS_COMMENT_COMMU CASCADE CONSTRAINTS;
DROP TABLE MBS_REPLY_COMMU CASCADE CONSTRAINTS;
DROP TABLE MBS_BOARD_RECOM CASCADE CONSTRAINTS;
DROP TABLE MBS_COMMENT_RECOM CASCADE CONSTRAINTS;
DROP TABLE MBS_REPLY_RECOM CASCADE CONSTRAINTS;
DROP TABLE MBS_IMG_FILE CASCADE CONSTRAINTS;
DROP TABLE MBS_TEST_LIST CASCADE CONSTRAINTS;
DROP TABLE MBS_TEST_RESULT CASCADE CONSTRAINTS;
DROP TABLE MBS_TEST_QUESTION CASCADE CONSTRAINTS;
DROP TABLE MBS_TEST_ITEMS CASCADE CONSTRAINTS;


DROP SEQUENCE SEQ_SEN_MEMBER;
DROP SEQUENCE SEQ_PRO_MEMBER;
DROP SEQUENCE SEQ_SEN_MANAGE;
DROP SEQUENCE SEQ_RESULT_SERVEY;
DROP SEQUENCE SEQ_SURVEY_NUM;
DROP SEQUENCE SEQ_BOARD_INQU;
DROP SEQUENCE SEQ_INQU_ADMIN;
DROP SEQUENCE SEQ_BOARD_COMMU;
DROP SEQUENCE SEQ_COMMENT_COMMU;
DROP SEQUENCE SEQ_REPLY_COMMU;
DROP SEQUENCE SEQ_BOARD_RECOM;
DROP SEQUENCE SEQ_COMMENT_RECOM;
DROP SEQUENCE SEQ_REPLY_RECOM;
DROP SEQUENCE SEQ_TEST_RESULT;
DROP SEQUENCE SEQ_TEST_LIST;
DROP SEQUENCE SEQ_TEST_QUESTION;
DROP SEQUENCE SEQ_TEST_ITEMS;


CREATE SEQUENCE SEQ_SEN_MEMBER;
CREATE SEQUENCE SEQ_PRO_MEMBER;
CREATE SEQUENCE SEQ_SEN_MANAGE;
CREATE SEQUENCE SEQ_RESULT_SERVEY;
CREATE SEQUENCE SEQ_SURVEY_NUM;
CREATE SEQUENCE SEQ_BOARD_INQU;
CREATE SEQUENCE SEQ_INQU_ADMIN;
CREATE SEQUENCE SEQ_BOARD_COMMU;
CREATE SEQUENCE SEQ_COMMENT_COMMU;
CREATE SEQUENCE SEQ_REPLY_COMMU;
CREATE SEQUENCE SEQ_BOARD_RECOM;
CREATE SEQUENCE SEQ_COMMENT_RECOM;
CREATE SEQUENCE SEQ_REPLY_RECOM;
CREATE SEQUENCE SEQ_TEST_RESULT;
CREATE SEQUENCE SEQ_TEST_LIST;
CREATE SEQUENCE SEQ_TEST_QUESTION;
CREATE SEQUENCE SEQ_TEST_ITEMS;


CREATE TABLE MBS_PRO_MEMBER
(
    PRO_MEM_NUM             NUMBER
        CONSTRAINT PK_PRO_MEMBER PRIMARY KEY,
    PRO_MEM_NAME            VARCHAR2(200) NOT NULL,
    PRO_MEM_EMAIL           VARCHAR2(200) NOT NULL,
    PRO_MEM_PHONE_MID       NUMBER        NOT NULL,
    PRO_MEM_PHONE_BACK      NUMBER        NOT NULL,
    PRO_MEM_CERTIFICATION   NUMBER        NOT NULL,
    PRO_MEM_PASSWORD        VARCHAR2(200) NOT NULL,
    PRO_MEM_PASSWORD_VERIFY VARCHAR2(200) NOT NULL,
    CONSTRAINT UK_PRO_PHONE UNIQUE (PRO_MEM_PHONE_MID, PRO_MEM_PHONE_BACK)
);


CREATE TABLE MBS_SEN_MEMBER
(
    SEN_MEM_NUM             NUMBER
        CONSTRAINT PK_SEN_MEMBER PRIMARY KEY,
    SEN_MEM_NAME            VARCHAR2(200) NOT NULL,
    SEN_MEM_BIRTH           DATE,
    SEN_MEM_PHONE_MID       NUMBER        NOT NULL,
    SEN_MEM_PHONE_BACK      NUMBER        NOT NULL,
    SEN_MEM_CERTIFICATION   NUMBER        NOT NULL,
    SEN_MEM_PASSWORD        VARCHAR2(200) NOT NULL,
    SEN_MEM_PASSWORD_VERIFY VARCHAR2(200) NOT NULL,
    PRO_MEM_NUM             NUMBER        NOT NULL,
    CONSTRAINT FK_SEN_MEMBER FOREIGN KEY (PRO_MEM_NUM) REFERENCES MBS_PRO_MEMBER (PRO_MEM_NUM),
    CONSTRAINT UK_SEN_PHONE UNIQUE (SEN_MEM_PHONE_MID, SEN_MEM_PHONE_BACK)
);


CREATE TABLE MBS_SURVEY
(
    SURVEY_QUEST_NUM      NUMBER
        CONSTRAINT PK_SURVEY PRIMARY KEY,
    SURVEY_QUEST_CONTENTS VARCHAR2(500) NOT NULL
);


CREATE TABLE MBS_RESULT_SURVEY
(
    RESULT_SURVEY_SEQ   NUMBER
        CONSTRAINT PK_RESULT_SURVEY PRIMARY KEY,
    RESULT_SURVEY_DATE  DATE DEFAULT SYSDATE,
    RESULT_SURVEY_SCORE NUMBER NOT NULL,
    PRO_MEM_NUM         NUMBER NOT NULL,
    CONSTRAINT FK_RESULT_SURVEY FOREIGN KEY (PRO_MEM_NUM) REFERENCES MBS_PRO_MEMBER (PRO_MEM_NUM)
);


CREATE TABLE MBS_BOARD_INQU
(
    BOARD_INQU_NUM         NUMBER
        CONSTRAINT PK_BOARD_INQU PRIMARY KEY,
    BOARD_INQU_TITLE       VARCHAR2(500)  NOT NULL,
    BOARD_INQU_CONTENTS    VARCHAR2(1000) NOT NULL,
    BOARD_INQU_FILE_LOCAL  VARCHAR2(500)  NULL,
    BOARD_INQU_FILE_SERVER VARCHAR2(500)  NULL,
    BOARD_INQU_DATE        DATE DEFAULT SYSDATE,
    PRO_MEM_NUM            NUMBER         NOT NULL,
    CONSTRAINT FK_BOARD_INQU FOREIGN KEY (PRO_MEM_NUM) REFERENCES MBS_PRO_MEMBER (PRO_MEM_NUM)
);


CREATE TABLE MBS_INQU_ADMIN
(
    INQU_ADMIN_NUM      NUMBER
        CONSTRAINT PK_INQU_ADMIN PRIMARY KEY,
    INQU_ADMIN_DATE     DATE DEFAULT SYSDATE,
    INQU_ADMIN_CONTENTS VARCHAR2(500) NOT NULL,
    INQU_ADMIN_AD       VARCHAR2(100) NOT NULL,
    BOARD_INQU_NUM      NUMBER        NOT NULL,
    CONSTRAINT FK_INQU_ADMIN FOREIGN KEY (BOARD_INQU_NUM) REFERENCES MBS_BOARD_INQU (BOARD_INQU_NUM)
);


CREATE TABLE MBS_BOARD_COMMU
(
    BOARD_COMMU_NUM         NUMBER
        CONSTRAINT PK_BOARD_COMMU PRIMARY KEY,
    BOARD_COMMU_TITLE       VARCHAR2(500) NOT NULL,
    BOARD_COMMU_CONTENTS    VARCHAR2(500) NOT NULL,
    BOARD_COMMU_FILE_LOCAL  VARCHAR2(500) NULL,
    BOARD_COMMU_FILE_SERVER VARCHAR2(500) NULL,
    BOARD_COMMU_DATE        DATE DEFAULT SYSDATE,
    PRO_MEM_NUM             NUMBER        NOT NULL,
    CONSTRAINT FK_BOARD_COMMU FOREIGN KEY (PRO_MEM_NUM) REFERENCES MBS_PRO_MEMBER (PRO_MEM_NUM)
);


CREATE TABLE MBS_COMMENT_COMMU
(
    COMMENT_COMMU_NUM      NUMBER
        CONSTRAINT PK_COMMENT_COMMU PRIMARY KEY,
    COMMENT_COMMU_DATE     DATE DEFAULT SYSDATE,
    COMMENT_COMMU_CONTENTS VARCHAR2(500) NOT NULL,
    BOARD_COMMU_NUM        NUMBER        NOT NULL,
    PRO_MEM_NUM            NUMBER        NOT NULL,
    CONSTRAINT FK_COMMENT_COMMU FOREIGN KEY (BOARD_COMMU_NUM) REFERENCES MBS_BOARD_COMMU (BOARD_COMMU_NUM),
    CONSTRAINT FK_COMMENT_COMMU_WHO FOREIGN KEY (PRO_MEM_NUM) REFERENCES MBS_PRO_MEMBER (PRO_MEM_NUM)
);


CREATE TABLE MBS_REPLY_COMMU
(
    REPLY_COMMU_NUM      NUMBER
        CONSTRAINT PK_REPLY_COMMU PRIMARY KEY,
    REPLY_COMMU_DATE     DATE DEFAULT SYSDATE,
    REPLY_COMMU_CONTENTS VARCHAR2(500) NOT NULL,
    COMMENT_COMMU_NUM    NUMBER,
    PRO_MEM_NUM          NUMBER        NOT NULL,
    CONSTRAINT FK_REPLY_COMMU FOREIGN KEY (COMMENT_COMMU_NUM) REFERENCES MBS_COMMENT_COMMU (COMMENT_COMMU_NUM),
    CONSTRAINT FK_REPLY_COMMU_WHO FOREIGN KEY (PRO_MEM_NUM) REFERENCES MBS_PRO_MEMBER (PRO_MEM_NUM)
);



CREATE TABLE MBS_BOARD_RECOM
(
    BOARD_RECOM_NUM      NUMBER
        CONSTRAINT PK_BOARD_RECOM PRIMARY KEY,
    BOARD_RECOM_TITLE    VARCHAR2(500) NOT NULL,
    BOARD_RECOM_CONTENTS VARCHAR2(500) NOT NULL,
    BOARD_RECOM_DATE     DATE DEFAULT SYSDATE,
    PRO_MEM_NUM          NUMBER        NOT NULL,
    CONSTRAINT FK_BOARD_RECOM FOREIGN KEY (PRO_MEM_NUM) REFERENCES MBS_PRO_MEMBER (PRO_MEM_NUM)
);



CREATE TABLE MBS_COMMENT_RECOM
(
    COMMENT_RECOM_NUM      NUMBER
        CONSTRAINT PK_COMMENT_RECOM PRIMARY KEY,
    COMMENT_RECOM_DATE     DATE DEFAULT SYSDATE NOT NULL,
    COMMENT_RECOM_CONTENTS VARCHAR2(500)        NOT NULL,
    BOARD_RECOM_NUM        NUMBER               NOT NULL,
    PRO_MEM_NUM            NUMBER               NOT NULL,
    CONSTRAINT FK_COMMENT_RECOM FOREIGN KEY (BOARD_RECOM_NUM) REFERENCES MBS_BOARD_RECOM (BOARD_RECOM_NUM),
    CONSTRAINT FK_COMMENT_RECOM_WHO FOREIGN KEY (PRO_MEM_NUM) REFERENCES MBS_PRO_MEMBER (PRO_MEM_NUM)
);


CREATE TABLE MBS_REPLY_RECOM
(
    REPLY_RECOM_NUM      NUMBER
        CONSTRAINT PK_REPLY_RECOM PRIMARY KEY,
    REPLY_RECOM_DATE     DATE DEFAULT SYSDATE,
    REPLY_RECOM_CONTENTS VARCHAR2(500) NOT NULL,
    COMMENT_RECOM_NUM    NUMBER,
    PRO_MEM_NUM          NUMBER        NOT NULL,
    CONSTRAINT FK_REPLY_RECOM FOREIGN KEY (COMMENT_RECOM_NUM) REFERENCES MBS_COMMENT_RECOM (COMMENT_RECOM_NUM),
    CONSTRAINT FK_REPLY_RECOM_WHO FOREIGN KEY (PRO_MEM_NUM) REFERENCES MBS_PRO_MEMBER (PRO_MEM_NUM)
);


CREATE TABLE MBS_IMG_FILE
(
    IMG_FILE_SEQ    NUMBER
        CONSTRAINT PK_IMG_FILE PRIMARY KEY,
    IMG_FILE_USER   VARCHAR2(500) NOT NULL,
    IMG_FILE_SERVER VARCHAR2(500) NOT NULL,
    BOARD_RECOM_NUM NUMBER        NOT NULL,
    CONSTRAINT FK_IMG_FILE FOREIGN KEY (BOARD_RECOM_NUM) REFERENCES MBS_BOARD_RECOM (BOARD_RECOM_NUM)
);


CREATE TABLE MBS_TEST_LIST
(
    TEST_LIST_NUM   NUMBER
        CONSTRAINT PK_TEST_LIST PRIMARY KEY,
    TEST_LIST_NAME  VARCHAR2(200) NOT NULL,
    TEST_LIST_DIFFI VARCHAR2(100) NOT NULL,
    TEST_LIST_AGE   VARCHAR2(200) NOT NULL
);



CREATE TABLE MBS_TEST_RESULT
(
    TEST_RESULT_SEQ   NUMBER
        CONSTRAINT PK_TEST_RESULT PRIMARY KEY,
    TEST_RESULT_DATE  DATE DEFAULT SYSDATE,
    TEST_RESULT_SCORE NUMBER NOT NULL,
    SEN_MEM_NUM       NUMBER NOT NULL,
    TEST_LIST_NUM     NUMBER NOT NULL,
    CONSTRAINT FK_TEST_RESULT_WHO FOREIGN KEY (SEN_MEM_NUM) REFERENCES MBS_SEN_MEMBER (SEN_MEM_NUM),
    CONSTRAINT FK_TEST_RESULT FOREIGN KEY (TEST_LIST_NUM) REFERENCES MBS_TEST_LIST (TEST_LIST_NUM)
);



CREATE TABLE MBS_TEST_QUESTION
(
    TEST_QUEST_SEQ      NUMBER
        CONSTRAINT PK_TEST_QUESTION PRIMARY KEY,
    TEST_QUEST_NUM      NUMBER        NOT NULL,
    TEST_QUEST_CONTENTS VARCHAR2(500) NOT NULL,
    TEST_QUEST_IMG      VARCHAR2(500) NULL,
    TEST_QUEST_ANSWER   VARCHAR2(200) NOT NULL,
    TEST_LIST_NUM       NUMBER        NOT NULL,
    CONSTRAINT FK_TEST_QUESTION FOREIGN KEY (TEST_LIST_NUM) REFERENCES MBS_TEST_LIST (TEST_LIST_NUM)
);


CREATE TABLE MBS_TEST_ITEMS
(
    TEST_QUEST_SEQ  NUMBER
        CONSTRAINT PK_TEST_ITEMS PRIMARY KEY,
    TEST_ITEM_ONE   VARCHAR2(100) NOT NULL,
    TEST_ITEM_TWO   VARCHAR2(100) NOT NULL,
    TEST_ITEM_THREE VARCHAR2(100) NOT NULL,
    TEST_ITEM_FOUR  VARCHAR2(100) NOT NULL,
    CONSTRAINT FK_TEST_ITEMS FOREIGN KEY (TEST_QUEST_SEQ) REFERENCES MBS_TEST_QUESTION (TEST_QUEST_SEQ)
);